CREATE DATABASE Teste;

GO

USE Teste;

CREATE TABLE Cidade(

	Cidade_Codigo INT PRIMARY KEY IDENTITY(1,1),
	Cidade_Descricao VARCHAR(75) NOT NULL

);

INSERT INTO Cidade VALUES('RECIFE');
INSERT INTO Cidade VALUES('PORTO ALEGRE');
INSERT INTO Cidade VALUES('CURITIBA');
INSERT INTO Cidade VALUES('BELO HORIZONTE');
INSERT INTO Cidade VALUES('SÃO PAULO');
INSERT INTO Cidade VALUES('RIO DE JANEIRO');
INSERT INTO Cidade VALUES('SALVADOR');

CREATE TABLE Vendedor(

	Vendedor_Codigo INT PRIMARY KEY IDENTITY(1,1),
	Vendedor_Descricao VARCHAR(75) NOT NULL,
	Cidade_Codigo INT FOREIGN KEY REFERENCES Cidade(Cidade_Codigo) NOT NULL

);

INSERT INTO Vendedor VALUES('JOSÉ MARIA', 1);
INSERT INTO Vendedor VALUES('ANTÔNIO',4);
INSERT INTO Vendedor VALUES('MARIA',2);
INSERT INTO Vendedor VALUES('EDUARDO',1);
INSERT INTO Vendedor VALUES('JOÃO',4);

CREATE TABLE Venda(

	Venda_Codigo INT PRIMARY KEY IDENTITY(1,1),
	Venda_Mes VARCHAR(10) NOT NULL,
	Venda_Total DECIMAL(8,2) NOT NULL,
	Venda_Comissao DECIMAL(8,2) NOT NULL,
	Vendedor_Codigo INT FOREIGN KEY REFERENCES Vendedor(Vendedor_Codigo) NOT NULL

);

INSERT INTO Venda VALUES('MAIO',1300,13,1);
INSERT INTO Venda VALUES('JUNHO',1500,15,1);
INSERT INTO Venda VALUES('JANEIRO',2000,20,2);
INSERT INTO Venda VALUES('JUNHO',1000,10,2);
INSERT INTO Venda VALUES('JANEIRO',500,5,3);
INSERT INTO Venda VALUES('FEVEREIRO',1000,10,3);
INSERT INTO Venda VALUES('MARÇO',2000,20,3);
INSERT INTO Venda VALUES('JUNHO',500,5,3);
INSERT INTO Venda VALUES('JUNHO',10000,100,4);
INSERT INTO Venda VALUES('SETEMBRO',1000,10,4);
INSERT INTO Venda VALUES('ABRIL',500,5,5);
INSERT INTO Venda VALUES('MAIO', 1200,10,5);
INSERT INTO Venda VALUES('JUNHO',3000,20,5);
INSERT INTO Venda VALUES('JULHO', 1500,5,5);